### ISSUE TITLE
Typescript usage

### ISSUE THREAD

**Issue by edqd** [neuronetio/deep-state-observer#2]
Hello,
first of all thanks for this lib, its a great thing for sharing state updates among microfrontends :) 

I have a question concerning typescript usage:
- type for ListenerFunction requires to return object (see https://github.com/neuronetio/deep-state-observer/blob/master/index.ts#L19), is this necessary?
Usually the listeners just pass the value to some other place without returning anything.

Thanks in advance

**Comment by neuronetio** [comment]
Yeah, it is not necessary, I will fix this soon, thanks 👍

**Comment by neuronetio** [comment]
fixed
